// <auto-generated />
using System;
using College_Information_and_Reporting_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace College_Information_and_Reporting_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251218184659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("College_Information_and_Reporting_System.Models.Attendance", b =>
                {
                    b.Property<int>("attendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("attendanceId"));

                    b.Property<int>("attendanceStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("attendanceTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.HasKey("attendanceId");

                    b.HasIndex("courseId");

                    b.HasIndex("studentId");

                    b.ToTable("attendances");
                });

            modelBuilder.Entity("College_Information_and_Reporting_System.Models.Course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("courseId"));

                    b.Property<decimal>("budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("courseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("startYear")
                        .HasColumnType("date");

                    b.HasKey("courseId");

                    b.HasIndex("departmentId");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("College_Information_and_Reporting_System.Models.Department", b =>
                {
                    b.Property<int>("departmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departmentId"));

                    b.Property<string>("departmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departmentHead")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("departmentId");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("College_Information_and_Reporting_System.Models.Student", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("studentDateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("studentEndDate")
                        .HasColumnType("date");

                    b.Property<int>("studentEthnicity")
                        .HasColumnType("int");

                    b.Property<string>("studentFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("studentGender")
                        .HasColumnType("int");

                    b.Property<string>("studentLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("studentStartDate")
                        .HasColumnType("date");

                    b.HasKey("studentId");

                    b.ToTable("students");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("coursescourseId")
                        .HasColumnType("int");

                    b.Property<int>("studentsstudentId")
                        .HasColumnType("int");

                    b.HasKey("coursescourseId", "studentsstudentId");

                    b.HasIndex("studentsstudentId");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("College_Information_and_Reporting_System.Models.Attendance", b =>
                {
                    b.HasOne("College_Information_and_Reporting_System.Models.Course", "course")
                        .WithMany()
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("College_Information_and_Reporting_System.Models.Student", "student")
                        .WithMany()
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("student");
                });

            modelBuilder.Entity("College_Information_and_Reporting_System.Models.Course", b =>
                {
                    b.HasOne("College_Information_and_Reporting_System.Models.Department", "department")
                        .WithMany("courseList")
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("College_Information_and_Reporting_System.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("coursescourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("College_Information_and_Reporting_System.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("studentsstudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("College_Information_and_Reporting_System.Models.Department", b =>
                {
                    b.Navigation("courseList");
                });
#pragma warning restore 612, 618
        }
    }
}
